#!/usr/bin/env php
<?php
use App\Command\OutputCommand;
use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

$application = new Application();
$application->add(new OutputCommand());
$application->run();
