#!/usr/bin/env php
<?php
use App\Command\StdInCommand;
use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

$application = new Application();
$application->add(new StdInCommand());
$application->run();
